# Generated by Django 4.2.1 on 2023-08-29 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Marka')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField(verbose_name='Yorum')),
                ('commentImg', models.ImageField(upload_to=None, verbose_name='Yorum Görseli')),
                ('commentDate', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(upload_to=None, verbose_name='Kullanıcı fotoğrafı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün başlığı')),
                ('product_img', models.ImageField(upload_to=None, verbose_name='Ürün fotoğrafı')),
                ('productColor', models.CharField(max_length=50, verbose_name='Renk kodunu gir')),
                ('productDesct', models.TextField(verbose_name='Ürün açıklaması')),
                ('productSıze', models.CharField(max_length=50, verbose_name='Ürünün boyutu')),
                ('productPrice', models.PositiveIntegerField(default=0, verbose_name='Ürünün fiyatı')),
                ('productGender', models.BooleanField(verbose_name='Ürünün Cinsiyeti')),
                ('productStock', models.PositiveIntegerField(verbose_name='Ürün stok')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.brand', verbose_name='Kullanıcı')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.comment', verbose_name='Kullanıcı')),
                ('liked', models.ManyToManyField(blank=True, related_name='liked_product', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
