# Generated by Django 4.2.1 on 2023-08-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_rename_product_img_product_producti_mg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productGender',
            field=models.CharField(choices=[('kadın', 'kadın'), ('erkek', 'erkek')], max_length=50, verbose_name='Ürünün Cinsiyeti'),
        ),
    ]
