# Generated by Django 4.2.1 on 2023-08-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_alter_product_productgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productGender',
            field=models.CharField(choices=[('Kadın', 'Kadın'), ('Erkek', 'Erkek')], max_length=50, verbose_name='Ürünün Cinsiyeti'),
        ),
    ]
