# Generated by Django 4.2.1 on 2023-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_alter_product_productgender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productSıze',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentImg',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Yorum Görseli'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productColor',
            field=models.CharField(max_length=50, verbose_name='Renk gir'),
        ),
    ]
