# Generated by Django 4.2.1 on 2023-09-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_comment_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
